about:
  summary: ESP variants
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  number: 0
extra:
  authors: jrb
  extra-files: []
  genome-build: GRCh37
  keywords:
  - ESP
  species: Homo_sapiens
package:
  name: grch37-esp-variants
  version: '1'
requirements:
  build:
  - grch37-reference-genome
  - gsort
  - htslib
  - perl
  - vt
  - zlib
  run:
  - grch37-reference-genome
  - gsort
  - htslib
  - perl
  - vt
  - zlib
source:
  path: .
